export const indianCities = [
    "Agra", "Ahmedabad", "Ahmednagar", "Aizawl", "Ajmer", "Akola", "Aligarh", "Allahabad", "Alwar", "Ambala", "Amravati", "Amritsar", "Anantapur", "Arrah", "Asansol", "Aurangabad",
    "Bangalore", "Bareilly", "Baroda", "Belgaum", "Bellary", "Berhampur", "Bhagalpur", "Bharatpur", "Bhatinda", "Bhavnagar", "Bhilai", "Bhilwara", "Bhiwandi", "Bhopal", "Bhubaneswar", "Bhuj", "Bikaner", "Bilaspur", "Bokaro",
    "Calicut", "Chandigarh", "Chandrapur", "Chennai", "Chittoor", "Coimbatore", "Cuttack",
    "Dadar", "Dehradun", "Delhi", "Dhanbad", "Dhule", "Dibrugarh", "Dimapur", "Durgapur",
    "Erode", "Etawah",
    "Faridabad", "Firozabad",
    "Gandhinagar", "Gangtok", "Gaya", "Ghaziabad", "Gorakhpur", "Gulbarga", "Guntur", "Guwahati", "Gwalior",
    "Haldia", "Haridwar", "Hisar", "Howrah", "Hubli", "Hyderabad",
    "Imphal", "Indore", "Itanagar",
    "Jabalpur", "Jaipur", "Jalandhar", "Jalgaon", "Jalna", "Jammu", "Jamnagar", "Jamshedpur", "Jhansi", "Jodhpur", "Junagadh",
    "Kakinada", "Kalyan", "Kanpur", "Kanyakumari", "Karimnagar", "Karnal", "Kochi", "Kolhapur", "Kolkata", "Kota", "Kottayam", "Kurnool",
    "Latur", "Lucknow", "Ludhiana",
    "Madurai", "Malegaon", "Mangalore", "Mathura", "Meerut", "Mirzapur", "Moradabad", "Mumbai", "Muzaffarnagar", "Muzaffarpur", "Mysore",
    "Nanded", "Nagar", "Nagpur", "Nashik", "Navi Mumbai", "Nellore", "New Delhi", "Nizamabad", "Noida",
    "Ooty",
    "Panaji", "Panipat", "Parbhani", "Patiala", "Patna", "Pondicherry", "Pune", "Puri", "Purnia",
    "Raichur", "Raipur", "Rajahmundry", "Rajkot", "Rampur", "Ranchi", "Ratlam", "Rewa", "Rohtak", "Rourkela",
    "Sagar", "Saharanpur", "Salem", "Sangli", "Satara", "Satna", "Secunderabad", "Shillong", "Shimla", "Shivamogga", "Silchar", "Siliguri", "Solapur", "Srinagar", "Surat",
    "Thane", "Thanjavur", "Thiruvananthapuram", "Thrissur", "Tiruchirappalli", "Tirunelveli", "Tirupati", "Tiruppur", "Tumkur",
    "Udaipur", "Ujjain", "Ulhasnagar",
    "Vadodara", "Varanasi", "Vasai-Virar", "Vellore", "Vijayawada", "Visakhapatnam",
    "Warangal",
    "Yamunanagar"
];
